version: '3.8'

services:
  validator_service:
    build: .
    command: python service1_validator.py
    environment:
      - MONGO_URI=${MONGO_URI}

  welcome_service:
    build: .
    command: python service2_welcome.py
    environment:
      - MONGO_URI=${MONGO_URI}

  offer_service:
    build: .
    command: python service3_offer.py
    environment:
      - MONGO_URI=${MONGO_URI}